# Site
repository: lvenier/lvenier.github.io
favicon: images/laurent.ico

# Personal info
name: Laurent Venier
title: IT Manager
company: SaasHup
current: Nancy, FR
email: lav@saashup.com
phone: 00352691482900
website: https://saashup.com
stack: | 
  [![StackShare](https://img.shields.io/badge/tech-stack-0690fa.svg?style=flat)](https://stackshare.io/lvenier/my-stack)

# Social links
google_analytics: UA-143362902-1
github_username:  lvenier
youtube_username: lvenier

# About Section
about_profile_image: images/laurent.jpg
about_content: |
  Welcome, my name's Laurent and I'm a senior IT Manager. As well as managing people, I also have experience administrating systems and making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Work</mark> and <mark>Sports</mark>

  <a href=""><img src="/images/badges/itil.png"></img></a>
  <a href=""><img src="/images/badges/scrum.jpg"></img></a>

more_content: | 
  Alongside my interests in IT some of my other interests and hobbies are:
   - Familly :)
   - Gaming
   - Working

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jemoji
