# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Laurent Venier
title: IT Manager
email: lav@yoctu.com
website: https://yoctu.com

# Social links
#twitter_username: lvenier
github_username:  lvenier
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: lvenier
#linkedin_username: lvenier
# pinterest_username: jekyll
youtube_username: lvenier
googleplus_username: +lvenier

# About Section
# about_title: About Me
about_profile_image: laurent.jpg
about_content: |
  Welcome, my name's Laurent and I'm a senior IT Manager. As well as managing people, I also have experience administrating systems and making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Work</mark> and <mark>Sports</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in IT some of my other interests and hobbies are:
   - Familly :)
   - Gaming
   - Working

# Footer
footer_show_references: true

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
