# Site
repository: lvenier/lvenier.github.io
favicon: images/laurent.ico

# Personal info
name: Laurent Venier
title: IT Manager
current: New York, USA
email: lav@yoctu.com
phone: 00352691482900
website: https://yoctu.com

# Social links
google_analytics: UA-143362902-1
github_username:  lvenier
youtube_username: lvenier
googleplus_username: +lvenier

# About Section
about_profile_image: images/laurent.jpg
about_content: |
  Welcome, my name's Laurent and I'm a senior IT Manager. As well as managing people, I also have experience administrating systems and making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Work</mark> and <mark>Sports</mark>

more_content: | 
  Alongside my interests in IT some of my other interests and hobbies are:
   - Familly :)
   - Gaming
   - Working

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
